import pandas as pd
import numpy as np
import mlflow
import mlflow.sklearn
import optuna
import os
import shutil
import math
from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.metrics import f1_score, roc_auc_score, classification_report
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from mlflow.tracking import MlflowClient
from feast import FeatureStore

optuna.logging.set_verbosity(optuna.logging.WARNING)

store = FeatureStore(repo_path="/Users/tribhangind/Documents/GitHub/RealTimeMLPipeline/feature_store")

MERCHANT_CATEGORIES = ["grocery", "electronics", "travel", "dining", "gas", "atm_withdrawal", "luxury_retail", "pharmacy"]
le = LabelEncoder()
le.fit(MERCHANT_CATEGORIES)

FEATURE_COLS = [
    "amount",
    "transaction_count_last_24h",
    "avg_amount_last_24h",
    "latitude",
    "longitude",
    "velocity_kmh",
    "merchant_category_enc",
    "mean_amount_30d",
    "std_amount_30d",
    "z_score_amount",
]

def get_training_data():
    """
    Load the enriched parquet generated by generate_data.py.
    All domain features (velocity, z-score, merchant) are pre-computed there.
    We use Feast historical features as a validation / training path.
    For speed here we read directly from the parquet which already has all columns.
    """
    df = pd.read_parquet(
        "/Users/tribhangind/Documents/GitHub/RealTimeMLPipeline/feature_store/data/transactions.parquet"
    )
    df["merchant_category_enc"] = le.transform(
        df["merchant_category"].fillna("grocery")
    )
    df = df.fillna(0)
    return df

def train_model(X_train, y_train, X_test, y_test, model_type="gb"):
    mlflow.set_experiment(f"fraud_v2_{model_type}")

    def objective(trial):
        with mlflow.start_run(nested=True):
            if model_type == "lr":
                params = {"C": trial.suggest_float("C", 1e-3, 1e2, log=True), "solver": "liblinear"}
                model = LogisticRegression(**params)
            elif model_type == "rf":
                params = {
                    "n_estimators": trial.suggest_int("n_estimators", 50, 300),
                    "max_depth": trial.suggest_int("max_depth", 3, 20),
                    "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
                }
                model = RandomForestClassifier(**params)
            elif model_type == "gb":
                params = {
                    "max_iter": trial.suggest_int("max_iter", 100, 500),
                    "max_depth": trial.suggest_int("max_depth", 3, 15),
                    "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
                    "l2_regularization": trial.suggest_float("l2_regularization", 0.0, 1.0),
                }
                model = HistGradientBoostingClassifier(**params)

            model.fit(X_train, y_train)
            preds = model.predict(X_test)
            f1 = f1_score(y_test, preds)
            mlflow.log_params(params)
            mlflow.log_metric("f1_score", f1)
            return f1

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=10)

    print(f"  [{model_type}] best F1={study.best_value:.4f} params={study.best_params}")

    model_path = f"/Users/tribhangind/Documents/GitHub/RealTimeMLPipeline/models/{model_type}_model_v2"
    if os.path.exists(model_path):
        shutil.rmtree(model_path)

    with mlflow.start_run() as run:
        if model_type == "lr":
            final = LogisticRegression(**study.best_params)
        elif model_type == "rf":
            final = RandomForestClassifier(**study.best_params)
        elif model_type == "gb":
            final = HistGradientBoostingClassifier(**study.best_params)

        final.fit(X_train, y_train)
        preds = final.predict(X_test)
        f1  = f1_score(y_test, preds)
        auc = roc_auc_score(y_test, final.predict_proba(X_test)[:, 1])
        mlflow.log_params(study.best_params)
        mlflow.log_metric("f1_score", f1)
        mlflow.log_metric("roc_auc",  auc)
        mlflow.sklearn.log_model(final, artifact_path="model", registered_model_name=f"fraud_v2_{model_type}")
        mlflow.sklearn.save_model(final, model_path)

    return f1, run.info.run_id

if __name__ == "__main__":
    print("Loading enriched training data from Feast...")
    df = get_training_data()
    print(f"Dataset: {len(df)} rows, fraud rate: {df['is_fraud'].mean()*100:.1f}%")

    X = df[FEATURE_COLS]
    y = df["is_fraud"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    smote = SMOTE(random_state=42)
    X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
    print(f"After SMOTE: {X_train_res.shape[0]} training samples, {y_train_res.sum()} fraud")

    results = {}
    for mtype in ["lr", "rf", "gb"]:
        print(f"\nTraining {mtype.upper()}...")
        f1, run_id = train_model(X_train_res, y_train_res, X_test, y_test, mtype)
        results[mtype] = {"f1": f1, "run_id": run_id}

    # Champion selection
    champion_mtype = max(results, key=lambda k: results[k]["f1"])
    champion_run_id = results[champion_mtype]["run_id"]
    print(f"\nChampion: {champion_mtype.upper()} with F1={results[champion_mtype]['f1']:.4f}")

    mlflow.register_model(f"runs:/{champion_run_id}/model", "fraud_detection_champion_v2")
    print(f"Registered 'fraud_detection_champion_v2'")

    # Materialize
    print("\nMaterializing...")
    os.system(
        f"cd /Users/tribhangind/Documents/GitHub/RealTimeMLPipeline/feature_store && "
        f"/Users/tribhangind/Documents/GitHub/RealTimeMLPipeline/.venv/bin/feast materialize-incremental {datetime.now().isoformat()}"
    )
